### ISSUE TITLE
Проблема с timing preset в full assist и quick setup

### ISSUE THREAD

**Issue by MaxBu** [efosamark/4IFIR-Wizard#26]
Приветствую. Обнаружил проблемы с установкой time preset 5 и 6:

1. При использовании quick setup для timing preset 5 не отображалось current значение, хотя в full assist оно было установлено (значение = 5). В чате обсуждения 4ifir подсказали, что этот пункт забагован и устанавиливает значение 7.
2. Full Assist и quick setup устанавливают неверные значения для timing preset 6. Выбирал значение 3, но в KIP отображается 4.
![баг 6 тайминг](https://github.com/efosamark/4IFIR-Wizard/assets/10898637/ca16b4a2-a866-4cf1-b826-ad7806d80264)
![баг 6 тайминг_значение](https://github.com/efosamark/4IFIR-Wizard/assets/10898637/b1582913-f101-4913-a1ee-0a1942b539fd)
![не отображается текущее значение 5 тайминга](https://github.com/efosamark/4IFIR-Wizard/assets/10898637/f4cd4241-a5f6-432c-ba52-32eae410ea32)

Версия чифира 4IFIR BETA HOS16 (12.11.2023 06:32AM). Версия 4IFIR-Wizard 2.0.6. Версия Uberhand-Overlay 2.0.1

**Comment by efosamark** [comment]
Hi. Thank you for the report.
The issue was identified and will be fixed in the next update.
Thank you for your patience.
