### ISSUE TITLE
В Full Assist на шаге выбора значений для Core Timings 1-7 представлены неполные списки вариантов 

### ISSUE THREAD

**Issue by kapez92** [efosamark/4IFIR-Wizard#28]
В Full Assist на шаге выбора значений для Core Timings 1-7 представлены неполные списки вариантов.

Пример:
 Timings Preset 6 имеет на выбор только значения 1,3,7

![photo_2023-11-15_14-02-18](https://github.com/efosamark/4IFIR-Wizard/assets/63586742/b9529c6f-1738-4240-8ae0-f86250cb0d40)

**Comment by efosamark** [comment]
Hi. The full assist feature is tailored towards having only minimal viable options. In order to get the full range of available values - please navigate to Manual Configuration menu.

**Comment by kapez92** [comment]
ok, got it. If there is only a minimal setting, then in theory you should leave only the value 1, as this option will work for everyone.

**Comment by efosamark** [comment]
Minimal viable, meaning that you have an option to use low, medium or high timings. Now lowest or highest - for that you need advanced configuration, which product also provides.

**Comment by kapez92** [comment]
Understood. This means that timings need to be configured more precisely separately in the advanced menu
