### ISSUE TITLE
CPU High Undervolt Mode JSON issue

### ISSUE THREAD

**Issue by Ebush1yKoz** [efosamark/4IFIR-Wizard#30]
When I get to the "CPU High Undervolt Mode" stage and select "No" after an unsuccessful selection, I get an error message: JSON file not found. Version 2.0.7

![IMG_5631](https://github.com/efosamark/4IFIR-Wizard/assets/150922077/bc84b84b-460c-4d4d-addf-c4f82f7895c0)

**Comment by MaxBu** [comment]
I also get this error
