### ISSUE TITLE
Erista 1113 MHz voltage and 3 GPU steps

### ISSUE THREAD

**Issue by saaaaaaaaaaaaaaaaaas** [efosamark/4IFIR-Wizard#49]
Could you please add less voltage for 1113 MHz GPU clock speed on Erista models? 1050mV is too high and 3 of 3 Eristas that tested this voltage works completely fine. 990mV and higher vould be great. Also could you add 3 more GPU steps for Erista with bigger list of voltages to pick up? (1152 MHz, 1190 MHz, 1228 Mhz)

**Comment by efosamark** [comment]
Please check version 2.0.11 to see if it satisfies your request.

**Comment by saaaaaaaaaaaaaaaaaas** [comment]
Absolutely nothing was changed. Can't see clocks higher than 1113 MHz and voltage of that clock lower than 1050mV. I even downloaded Wizard manualy (to see if i was wrong) and on config and .json file nothing has changed or added for Erista models.

**Comment by efosamark** [comment]
For unlocking clocks - contact 4IFIR Dev.
For lower voltages - I will try not to forget add it later.

**Comment by saaaaaaaaaaaaaaaaaas** [comment]
Those clocks (1152 MHz, 1190 MHz, 1228 Mhz) are already added by 4IFIR Dev. for Erista models but we can't use them because they don't exist in Wizard at the moment. (from the words of 4IFIR Dev.)

**Comment by efosamark** [comment]
If the clocks are there - there is no need to use Wizard by default. 
Although, if they need to be added - I need to see the updated tables.

Until then the issue is closed.

**Comment by saaaaaaaaaaaaaaaaaas** [comment]
[customize.zip](https://github.com/efosamark/4IFIR-Wizard/files/13928738/customize.zip)
Here it is
